#include "musab_lang.h"

// Code generator for Musab Language
// Generates x86-64 assembly from AST

void codegen(Obj *prog, FILE *out) {
  fprintf(out, "; Musab Language - x86-64 Assembly\n");
  fprintf(out, "; Generated by musab-cc\n\n");
  
  fprintf(out, "section .text\n");
  fprintf(out, "  global main\n\n");
  
  fprintf(out, "main:\n");
  fprintf(out, "  push rbp\n");
  fprintf(out, "  mov rbp, rsp\n");
  
  // Placeholder: simple return 0
  fprintf(out, "  xor eax, eax\n");
  fprintf(out, "  pop rbp\n");
  fprintf(out, "  ret\n");
  
  fprintf(out, "\nsection .data\n");
  fprintf(out, "  ; Global variables would go here\n");
}
